const { google } = require('googleapis');
const crypto = require('crypto');

// Resolves which spreadsheet to use for this request.
//
// CUSTOMERS_SHEET_ID not set  -> single-user mode: always GOOGLE_SHEET_ID.
// CUSTOMERS_SHEET_ID set      -> ?user=<name> AND ?t=<token> are required.
//                                <name> must match column A (case-insensitive)
//                                in the Customers sheet and <token> must match
//                                column F ("Token") on that same row. The sheet
//                                URL in that row is used. Missing user, missing
//                                token, unknown user or token mismatch -> null.
//                                Callers must answer 404 {error:"unknown user"}.
//                                GOOGLE_SHEET_ID is never used as a fallback
//                                in this mode.
//
// Customers sheet layout: A=name … F=Token (16 chars, a-z0-9), sheet URL in
// any other column of the row. Tokens are generated by pipeline_code.gs.

const TOKEN_COL = 5; // F
const TOKEN_RE = /^[a-z0-9]{16}$/;

const cache = new Map(); // "name\u0000token" -> { id, t }
const TTL = 5 * 60 * 1000;

function tokenMatches(expected, given) {
  const a = Buffer.from(String(expected || '').trim());
  const b = Buffer.from(String(given || ''));
  return a.length > 0 && a.length === b.length && crypto.timingSafeEqual(a, b);
}

async function resolveSheetId(req) {
  const customersId = process.env.CUSTOMERS_SHEET_ID;
  if (!customersId) return process.env.GOOGLE_SHEET_ID;

  const q = req.query || {};
  const user = (q.user ? String(q.user) : '').trim().toLowerCase();
  const token = (q.t ? String(q.t) : '').trim();
  if (!user || !TOKEN_RE.test(token)) return null;

  const key = user + '\u0000' + token;
  const hit = cache.get(key);
  if (hit && Date.now() - hit.t < TTL) return hit.id;

  const creds = JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT);
  const auth = new google.auth.GoogleAuth({
    credentials: creds,
    scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly']
  });
  const sheets = google.sheets({ version: 'v4', auth });
  let rows = [];
  for (const range of ["'Customers'!A1:H400", 'A1:H400']) {
    try {
      const resp = await sheets.spreadsheets.values.get({ spreadsheetId: customersId, range });
      rows = resp.data.values || [];
      if (rows.length) break;
    } catch (e) { /* tab name miss — try next */ }
  }
  for (const row of rows) {
    const name = (row[0] || '').toString().trim().toLowerCase();
    if (name !== user) continue;
    if (!tokenMatches(row[TOKEN_COL], token)) return null;
    for (const cell of row) {
      const m = /\/d\/([a-zA-Z0-9-_]+)/.exec((cell || '').toString());
      if (m) { cache.set(key, { id: m[1], t: Date.now() }); return m[1]; }
    }
    return null;
  }
  return null;
}

module.exports = { resolveSheetId };
